// 全球热点资讯源 — 科技+AI+世界+科学+开发+商业+中文
module.exports = [
  // ── 科技 ──
  { name: 'TechCrunch', type: 'rss', url: 'https://techcrunch.com/feed/', category: '科技', lang: 'en' },
  { name: 'The Verge', type: 'rss', url: 'https://www.theverge.com/rss/index.xml', category: '科技', lang: 'en' },
  { name: 'Ars Technica', type: 'rss', url: 'https://feeds.arstechnica.com/arstechnica/index', category: '科技', lang: 'en' },
  { name: 'Wired', type: 'rss', url: 'https://www.wired.com/feed/rss', category: '科技', lang: 'en' },
  { name: 'Engadget', type: 'rss', url: 'https://www.engadget.com/rss.xml', category: '科技', lang: 'en' },
  { name: 'Gizmodo', type: 'rss', url: 'https://gizmodo.com/feed', category: '科技', lang: 'en' },
  { name: 'CNET', type: 'rss', url: 'https://www.cnet.com/rss/news/', category: '科技', lang: 'en' },
  { name: 'BBC Tech', type: 'rss', url: 'https://feeds.bbci.co.uk/news/technology/rss.xml', category: '科技', lang: 'en' },
  { name: 'NYT Tech', type: 'rss', url: 'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml', category: '科技', lang: 'en' },
  { name: 'ZDNet', type: 'rss', url: 'https://www.zdnet.com/news/rss.xml', category: '科技', lang: 'en' },
  { name: 'Register', type: 'rss', url: 'https://www.theregister.com/headlines.atom', category: '科技', lang: 'en' },
  { name: 'The Register', type: 'rss', url: 'https://www.theregister.com/headlines.atom', category: '科技', lang: 'en' },
  { name: 'Toms Guide', type: 'rss', url: 'https://www.tomsguide.com/feeds/all', category: '科技', lang: 'en' },
  { name: 'TNW', type: 'rss', url: 'https://thenextweb.com/feed', category: '科技', lang: 'en' },
  { name: 'TechRepublic', type: 'rss', url: 'https://www.techrepublic.com/rssfeeds/articles/', category: '科技', lang: 'en' },
  // ── AI ──
  { name: 'MIT Tech Review', type: 'rss', url: 'https://www.technologyreview.com/feed/', category: 'AI', lang: 'en' },
  { name: 'OpenAI Blog', type: 'rss', url: 'https://openai.com/blog/rss.xml', category: 'AI', lang: 'en' },
  { name: 'Google AI Blog', type: 'rss', url: 'https://blog.google/technology/ai/rss/', category: 'AI', lang: 'en' },
  { name: 'HuggingFace', type: 'rss', url: 'https://huggingface.co/blog/feed.xml', category: 'AI', lang: 'en' },
  { name: 'VentureBeat AI', type: 'rss', url: 'https://venturebeat.com/category/ai/feed/', category: 'AI', lang: 'en' },
  { name: 'Analytics India', type: 'rss', url: 'https://analyticsindiamag.com/feed/', category: 'AI', lang: 'en' },
  // ── 世界 ──
  { name: 'BBC World', type: 'rss', url: 'https://feeds.bbci.co.uk/news/world/rss.xml', category: '世界', lang: 'en' },
  { name: 'NPR News', type: 'rss', url: 'https://feeds.npr.org/1001/rss.xml', category: '世界', lang: 'en' },
  { name: 'Guardian World', type: 'rss', url: 'https://www.theguardian.com/world/rss', category: '世界', lang: 'en' },
  { name: 'Al Jazeera', type: 'rss', url: 'https://www.aljazeera.com/xml/rss/all.xml', category: '世界', lang: 'en' },
  // ── 科学 ──
  { name: 'Nature News', type: 'rss', url: 'https://www.nature.com/nature.rss', category: '科学', lang: 'en' },
  { name: 'Science Daily', type: 'rss', url: 'https://www.sciencedaily.com/rss/all.xml', category: '科学', lang: 'en' },
  { name: 'New Scientist', type: 'rss', url: 'https://www.newscientist.com/feed/home/', category: '科学', lang: 'en' },
  { name: 'Space.com', type: 'rss', url: 'https://www.space.com/feeds/all', category: '科学', lang: 'en' },
  { name: 'LiveScience', type: 'rss', url: 'https://www.livescience.com/feeds/all', category: '科学', lang: 'en' },
  // ── 开发 ──
  { name: 'Hacker News', type: 'hn', url: 'https://hacker-news.firebaseio.com/v0', category: '开发', lang: 'en' },
  { name: 'Product Hunt', type: 'rss', url: 'https://www.producthunt.com/feed', category: '产品', lang: 'en' },
  { name: 'Slashdot', type: 'rss', url: 'https://rss.slashdot.org/Slashdot/slashdotMain', category: '开发', lang: 'en' },
  // ── 商业 ──
  { name: 'Bloomberg Tech', type: 'rss', url: 'https://feeds.bloomberg.com/technology/news.rss', category: '商业', lang: 'en' },
  { name: 'Forbes Tech', type: 'rss', url: 'https://www.forbes.com/innovation/feed/', category: '商业', lang: 'en' },
  { name: 'CNBC Tech', type: 'rss', url: 'https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19854910', category: '商业', lang: 'en' },
  // ── 中文源 ──
  { name: '36氪', type: 'rss', url: 'https://36kr.com/feed', category: '商业', lang: 'zh' },
  { name: '少数派', type: 'rss', url: 'https://sspai.com/feed', category: '科技', lang: 'zh' },
  { name: 'IT之家', type: 'rss', url: 'https://www.ithome.com/rss/', category: '科技', lang: 'zh' },
  { name: '虎嗅', type: 'rss', url: 'https://www.huxiu.com/rss/0.xml', category: '商业', lang: 'zh' },
  { name: '量子位', type: 'rss', url: 'https://www.qbitai.com/feed', category: 'AI', lang: 'zh' },
  { name: '机器人之心', type: 'rss', url: 'https://www.jiqizhixin.com/rss', category: 'AI', lang: 'zh' },
  { name: '爱范儿', type: 'rss', url: 'https://www.ifanr.com/feed', category: '科技', lang: 'zh' },
  // ── Reddit ──
  { name: 'Reddit r/worldnews', type: 'reddit', subreddit: 'worldnews', url: '', category: '世界', lang: 'en' },
  { name: 'Reddit r/technology', type: 'reddit', subreddit: 'technology', url: '', category: '科技', lang: 'en' },
  { name: 'Reddit r/science', type: 'reddit', subreddit: 'science', url: '', category: '科学', lang: 'en' },
  { name: 'Reddit r/artificial', type: 'reddit', subreddit: 'artificial', url: '', category: 'AI', lang: 'en' },
  // === NEW HIGH-FREQUENCY SOURCES ===
  { name: 'CNN Tech', type: 'rss', url: 'https://rss.cnn.com/rss/edition_technology.rss', category: '科技', lang: 'en' },
  { name: 'Reuters Tech', type: 'rss', url: 'https://www.reutersagency.com/feed/?best-topics=tech', category: '科技', lang: 'en' },
  { name: 'BleepingComputer', type: 'rss', url: 'https://www.bleepingcomputer.com/feed/', category: '科技', lang: 'en' },
  { name: 'TechSpot', type: 'rss', url: 'https://www.techspot.com/backend/rss', category: '科技', lang: 'en' },
  { name: 'MacRumors', type: 'rss', url: 'https://feeds.macrumors.com/MacRumors-All', category: '科技', lang: 'en' },
  { name: '9to5Mac', type: 'rss', url: 'https://9to5mac.com/feed/', category: '科技', lang: 'en' },
  { name: 'Android Authority', type: 'rss', url: 'https://www.androidauthority.com/feed/', category: '科技', lang: 'en' },
  { name: 'TechCrunch AI', type: 'rss', url: 'https://techcrunch.com/category/artificial-intelligence/feed/', category: 'AI', lang: 'en' },
  { name: 'The Decoder', type: 'rss', url: 'https://the-decoder.com/feed/', category: 'AI', lang: 'en' },
  { name: 'Ars Technica Science', type: 'rss', url: 'https://feeds.arstechnica.com/arstechnica/science', category: '科学', lang: 'en' },
  { name: 'Scientific American', type: 'rss', url: 'https://www.scientificamerican.com/feed/rss/', category: '科学', lang: 'en' },
  { name: 'Wired Science', type: 'rss', url: 'https://www.wired.com/feed/category/science/latest/rss', category: '科学', lang: 'en' },
  { name: 'Reuters World', type: 'rss', url: 'https://www.reutersagency.com/feed/?best-topics=political-general', category: '世界', lang: 'en' },
  { name: 'AP News', type: 'rss', url: 'https://rsshub.app/apnews/topics/apf-topnews', category: '世界', lang: 'en' },
  { name: 'Hacker News Best', type: 'rss', url: 'https://hnrss.org/best', category: '开发', lang: 'en' },
  { name: 'GitHub Trending', type: 'rss', url: 'https://rsshub.app/github/trending/daily/any', category: '开发', lang: 'en' },
  { name: 'TechNode', type: 'rss', url: 'https://technode.com/feed/', category: '科技', lang: 'zh' },
  { name: '极客公园', type: 'rss', url: 'https://www.geekpark.net/rss', category: '科技', lang: 'zh' },
  { name: 'PingWest', type: 'rss', url: 'https://www.pingwest.com/feed', category: '科技', lang: 'zh' },
  { name: '品玩', type: 'rss', url: 'https://www.pingwest.com/feed', category: '科技', lang: 'zh' }

];